# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
	config.vm.provision :shell, path: "bootstrap.sh"

	# To avoid an error, we add an hostname
	# Find out more here: http://blog.doismellburning.co.uk/2013/01/19/upgrading-puppet-in-vagrant-boxes/
	config.vm.hostname = "micro.de"

  config.vm.network "forwarded_port", guest: 5000, host: 5000

	config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "code", "/code/", create: true
  config.vm.synced_folder "exchange", "/exchange/", create: true

	# for defining a name
	config.vm.define "micro" do |s|
	end

  config.vm.provider "virtualbox" do |vb|
		# https://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working?rq=1
		# https://serverfault.com/questions/495914/vagrant-slow-internet-connection-in-guest
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			# comment the following line if there are too many DNS lookups
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

end
