# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
  end

  config.vm.provision 'shell', inline: <<-SHELL
    sudo apt-add-repository universe
    sudo apt-add-repository multiverse
    sudo apt-get update
    sudo echo 'allowed_users=anybod' >> /etc/X11/Xwrapper.config
    sudo apt-get install -y --no-install-recommends lubuntu-desktop
    sudo apt-get install -y virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
    sudo apt-get install -y openjdk-7-jdk openjdk-7-source eclipse
    sudo apt-get autoremove -y
    
    # enabling auto login
    sudo cat > /etc/lightdm/lightdm.conf <<EOL
[SeatDefaults]
autologin-user=vagrant
autologin-user-timeout=0
EOL

    eclipse \
    -application org.eclipse.equinox.p2.director \
    -noSplash \
    -repository \
    http://findbugs.cs.umd.edu/eclipse \
    -installIUs \
    edu.umd.cs.findbugs.plugin.eclipse.feature.group
    
    sudo reboot
  SHELL
end
