# -*- mode: ruby -*-
# vi: set ft=ruby :

# Config file is passed from level to level, top to bottom
# That is here first config, then web, then python, then GUI
Vagrant.configure(2) do |config| 
	config.vm.box = "ubuntu/trusty64"

  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end
  
  config.vm.define "python" do |p|
    # This vm will not see the host's vagrant directory (containing Vagrantfile)
		# but the subdirectory python. This way the machines may stay seperated.
		p.vm.synced_folder ".", "/vagrant", disabled: true
    p.vm.synced_folder "./python", "/vagrant", create: true
  end

  config.vm.define "gui" do |g|
		# Allow for GUI programs to be called via vagrant ssh <program>. Compression seems to be good.
		g.ssh.forward_x11 = true

		# VBoxControl options can be specified here. This will be called everytime the VM is started!
		# Permanent/one-time changes can be made via VBoxControl and the VirtualBox GUI.
		# Eventually in this file as well? 
    g.vm.provider "virtualbox" do |vb|
        # vb.gui specifies whether to start the VirtualBox GUI at startup.
				#vb.gui = true
        vb.memory = "1024"
    end
  end

end
